language: go
go:
- 1.6
- 1.7
- 1.8
- 1.9
sudo: false
install:
- go get -t -v ./...
notifications:
  slack:
    rooms:
      secure: eh8oSxLecI1fGV/2YgEsEWqT5OnvCY1gYJY+QqUJ4HmwNG2qgpsPlpfejAMCyIZVVdebU0HtBJVtsfVXK3XkBs+m8AU6CagQnZyMXtw41AFzk6rFtaWBHmQ4wesbFEIvesBe+JQuoKyYXhIzrC5teIfU9/TeozeTogmDGGWny8rkEubvkajSoxl2rd6210rzhX2tCLQ7JuYLXg6u02FpxvMWpYOc5BTznAwpH1AK+KFvBzUX7+kbpcz4KLllcGob2aix+uCIBzXxeqonlMTzMVUMfw4xJJncGdAtMuIZHTJuVbrLiBjCBaNTMVlImPPVacJGPm9H2wBLTwCi3rgGe82gRIm8t1nbbCSfkFyMcENBY41LZp3p3rJj7147DkRvEH5dsDkKSWNW6wAmeBSL+he+sFzS1tAXpe6phorzoBwV7GZ8OJpw2v6lbrznRd1GKvTbp5zWnmmg4208C5V/a2f53h/8a1Op0PK/tA5jdl39rtVu0EzL7N3e6K1r054XNlrDJM5vSVAd329gfp2ylUatEKmfpxgtbyTK1do9rAluuTfORrv7YFZVf25SpO4L+kKeX1NFBXW30hpuKKD9KXFPZ3tzc71ct39I4v211dz5vOuuxsqEUVYZFX3sDcqAeBz6cSDsQDDBIJ5pQPXbg1IctGeCNswrztw/I/yQr54=
