language: go
go:
- 1.6
- 1.7
- 1.8
- 1.9
sudo: false
install:
- go get -t -v ./...

notifications:
  slack:
    secure: UYF2ngDfgEg0gguuPTDBhCfhGRz2qsqffKpxqfNL7v/XOa194lpN97lQ1b66RYUo0JteDLiakrJk8vMVaZM1DouPmuX2jgd21BsYUTgSHnrltJyM9cXOMAVLvGzqWaSC3ecdcd6otf/51HkAvTFaEzWE/PYCUJWZ+xAHj5UZBfxkvnzPNkWlwQqX24duVLsJe1HPZ2KAWBZ5JPPtrsWQyySgr5iJAL7nMVFvUCegi8PE/C3t/f46fZ33d94LZYrP2AN3BZv6oL4+s+EPWbcEBjLTBoWdylYNp73yzBfmy+4v/PNFb2b6fXOahbYDMk9R8rpTtC/f8k2diaPFetLH0zQoZYz8JytX3erBpO3BZPSEEq+02oA+WP3xDB5LxOYq/A/hkfidN5GCo7NPT+dLrAh7mOmFgNF442YpoVT+DStRLnGMVjhB+5yCfc7UL4dp+CDzbGHX2QAUUpns16w/vo5TVpREwi7BlGS+cAeSI6gisbMx5V429Ncz9tYJxZyCFIWfGlmYsb0Wki6Vq3JLbv8UH9SNa0nJA0PaWdRoNvl3LQHzQOiPMY19QghwrKlpatnXbIzGXlCvwjfck810ic6umcl93FP8WO0fBt/TwrLiOOuGDS9XIah9udFrIjHQq+zkc8dXpQWx55M5ZQpR9oQ/uyTctAqbNwf1+wDfocY=
    
